version: 2.1

jobs:
  ejecutar-test:

    parameters:
      python_version:
        type: string

    docker:
      - image: parka015/serie-motion:<< matrix.python_version >>

    steps:
      - checkout

      - run:
          name: Run tests
          command: invoke test


workflows:
  integracion: 
    jobs:
      - ejecutar-test:
        matrix:
          parameters:
            python_version: ["3.6","3.10"]
