name: Publicar Imagen a Dockerhub
on:
  push:
    paths:
      - 'Dockerfile'
      - 'pyproject.toml'
      
jobs:   
  actualizarImagen:
    strategy:
      matrix:
        python_version: ["3.6", "3.10"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login en Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{  secrets.DOCKER_USERNAME  }}
          password: ${{  secrets.DOCKER_PASSWORD  }}

      - name: Construir contenedor version ${{ matrix.python_version }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: parka015/serie-motion:${{ matrix.python_version }}
          build-args: VERSION=${{ matrix.python_version }}

