name: Publicar Imagen a Dockerhub
on:
  push:
    paths:
      - 'Dockerfile'
      - 'pyproject.toml'
      
jobs:   
  actualizarImagen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Construir contenedor
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/serie-motion
          tags: latest

