name: Publicar a Dockerhub 
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      
jobs:
  dockerfile-changes:
    runs-on: ubuntu-latest
    outputs:
      update: ${{ steps.set-output.outputs.has_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Comprobar qué archivos han cambiado
        id: changed-files
        uses: tj-actions/changed-files@v1.2.0
        
        
      - name: Dockerfile o requerimientos han cambiado
        id: set-output
        if: |
          contains(steps.changed-files.outputs.modified_files, 'Dockerfile') ||
          contains(steps.changed-files.outputs.modified_files, 'pyproject.toml')
        run: echo '::set-output name=has_changed::true'
        
  build-container:
    runs-on: ubuntu-latest
    needs: dockerfile-changes
    if: needs.dockerfile-changes.outputs.update
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login en Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{  secrets.DOCKER_HUB_USERNAME  }}
          password: ${{  secrets.DOCKER_HUB_PASSWORD  }}
        
      - name: build y push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: parka015/serie-motion:latest
          labels: ${{  steps.meta.output.labels  }}
          
      - name: Sync readme
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{  secrets.DOCKER_USERNAME  }}
          password: ${{  secrets.DOCKER_PASSWORD  }}
          repository: parka015/SerieMotion-IV
          readme: "./README.md" 



